version: 2
updates:
  # Enable version updates for Go
  - package-ecosystem: "gomod"
    # Look for `go.mod` file in the `root` directory
    directory: "/"
    # Check the for updates every day (weekdays)
    schedule:
      interval: "monthly"
